version: '3.8'

services:
  app:
    build:
      context: server
      dockerfile: server/Dockerfile
    ports:
      - "4434:4434"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379"

